[colors.primary]
background = '#19120c'
foreground = '#efe0d6'

[colors.selection]
text = '#efe0d6'
background = '#6b3b04'

[colors.cursor]
text = '#19120c'
cursor = '#ffb779'

[colors.normal]
black   = '#19120c'
red     = '#ff736b'
green   = '#90ff79'
yellow  = '#ffe56b'
blue    = '#f2a059'
magenta = '#763804'
cyan    = '#ffb779'
white   = '#fff6ee'

[colors.bright]
black   = '#a59e98'
red     = '#ffa09a'
green   = '#b1ffa1'
yellow  = '#ffeea1'
blue    = '#ffc18d'
magenta = '#ffcca1'
cyan    = '#ffdec2'
white   = '#fffbf8'
